# Generated by Django 6.0.1 on 2026-01-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('partita_iva', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('indirizzo', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='codice_univoco',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descrizione',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reorder_level',
            new_name='ordine_riordino',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='prezzo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='prezzo_di_base',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='units_in_transit',
            new_name='unita_in_transito',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='units_sold_month',
            new_name='unita_vendute_mensili',
        ),
        migrations.AddField(
            model_name='product',
            name='fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fornitore'),
        ),
    ]
