# Generated by Django 6.0.1 on 2026-01-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fornitore_rename_category_product_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company',
            new_name='societa',
        ),
    ]
