# Generated by Django 6.0.1 on 2026-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_company_customuser_societa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
